# Generated by Django 5.0.6 on 2024-06-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=128)),
                ('usertag', models.CharField(max_length=128)),
                ('sub_date', models.DateField()),
            ],
        ),
    ]
